# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4e71e2c7a795b7aa41e3fb3ef8d659a7ef35b4124ef824e4694b301bfd6c5ab17f1471fbc5c4eb16cada0d54456cab1557060c54c3f09dfda36a88c5aad3c8f

test:
  secret_key_base: 6c45a329ef22fb34b73fb9e5a0eb3b491434f0705a204c0d10c945a77c25087fb1fd786268132cb66214216f2dfa24c06689d4a657b72956315f567173ca0654

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
